#!/usr/bin/env python3
"""Gate v3 — same-mechanism sham, a compositional positive arm, and calibration.

FOUR DEFECTS IN v2 THAT THIS FIXES

  1  THE SHAM WAS SYNTHESISED FROM THE OBSERVED DENOMINATOR, so after log D was
     controlled it carried no capture information at all — partial correlation
     with log capture given log D was +0.003 against the real program's +0.444.
     It lost 39 of 40 times to a program with no biology in it. The sham is now
     generated by the SAME MECHANISM, driven by the latent capture factor with
     an independent latent. On real data the analogue is a REAL GENE QUADRUPLE
     from the same nuclei; nothing synthesised can reproduce this.

  2  THE POSITIVE ARMS MOVED ONLY THE AMPLITUDE. Scaling all four partners by a
     common factor leaves a centred log-ratio unchanged BY CONSTRUCTION, so the
     composition channel was never exercised while a PASS would have read as
     though the whole estimator worked. POS-COMP moves the partners in opposing
     directions with the total held flat, so the only route from P to Q is the
     composition.

  3  THE ESTIMATOR FAILED OPEN, silently substituting Poisson for a failed
     negative-binomial fit. A failed fit must not become an apparent success
     through an unreported change of model. It now raises, and the family
     actually used is recorded in every result.

  4  NO GENE-SPECIFIC CAPTURE HETEROGENEITY. Each gene now has its own exponent
     on the capture factor, so capture does not act as one clean shared scalar.

WHAT THE GATE MUST SHOW, and it is not enough that the arms pass once

  Across independently generated datasets, in every regime — including two the
  sham construction was never tuned on — both negative arms must fail
  qualification and both positive arms must qualify. The sham draws are also
  checked for the two properties a null needs: that they reproduce the real
  program's residual capture dependence, and that they are not correlated with
  each other. A collection of 999 correlated or poorly matched shams is not a
  valid null however many of them there are.

No real expression is read. Nothing is trained.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "src"))
from sea_ad_jepa.v5.teacher_fidelity_core_v1 import (  # noqa: E402
    clr, run_directed_test)

N_DONORS = 27
STRATA_PER_DONOR = 4
CELLS_PER_STRATUM = 60
SEED = 20260927
ALPHA = 0.05
DONOR_FRACTION = 2.0 / 3.0

REGIMES = {
    "A_tuning_sparse":     dict(cap_sd=0.6, base=1.2),
    "B_tuning_dense":      dict(cap_sd=0.6, base=40.0),
    "C_untuned_highcap":   dict(cap_sd=1.0, base=1.2),
    "D_untuned_verysparse": dict(cap_sd=0.3, base=0.6),
}
ARMS = {
    "NEG":      dict(link="none",        want=False),
    "POS_AMP":  dict(link="amplitude",   want=True),
    "POS_COMP": dict(link="composition", want=True),
}


def sha_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for c in iter(lambda: fh.read(1 << 22), b""):
            h.update(c)
    return h.hexdigest()


def _partners(rng, base, cap, gamma, z, mode):
    """Four partner counts driven by the LATENT capture factor.

    mode 'amplitude'   all four scale together with z: composition flat
    mode 'composition' partners move in opposing directions, total held flat
    mode 'flat'        z does not enter at all
    """
    n = cap.size
    if mode == "amplitude":
        load = np.array([0.5, 0.5, 0.5, 0.5])
    elif mode == "composition":
        load = np.array([0.6, -0.6, 0.6, -0.6])   # sums to zero: total ~flat
    else:
        load = np.zeros(4)
    rate = base * np.exp(np.outer(z, load)) * (cap[:, None] ** gamma[None, :])
    return rng.poisson(np.maximum(rate, 1e-9))


def simulate(rng, *, cap_sd, base, link):
    donors, strata = [], []
    for d in range(N_DONORS):
        for s in range(STRATA_PER_DONOR):
            donors += [f"D{d:02d}"] * CELLS_PER_STRATUM
            strata += [f"D{d:02d}|op{s}"] * CELLS_PER_STRATUM
    donors = np.asarray(donors); strata = np.asarray(strata)
    n = donors.size

    cap = rng.lognormal(0.0, cap_sd, n)
    # gene-specific capture heterogeneity: capture is NOT one clean shared scalar
    gamma_P = rng.uniform(0.7, 1.3, 4)
    gamma_Q = rng.uniform(0.7, 1.3, 4)
    gamma_S = rng.uniform(0.7, 1.3, 4)
    lib = rng.negative_binomial(6, 6 / (6 + 4000.0 * cap)).astype(float) + 50.0
    D = np.maximum(lib, 1.0)

    zP = rng.normal(0, 1, n)
    zS = rng.normal(0, 1, n)                     # sham latent, independent
    if link == "none":
        zQ = rng.normal(0, 1, n)
    else:
        zQ = 0.8 * zP + rng.normal(0, 0.6, n)    # Q responds to P's latent

    # P carries its latent through the channel named by `link`; under 'none' it
    # still has structure, it is simply unrelated to Q
    p_mode = "amplitude" if link in ("none", "amplitude") else "composition"
    NP4 = _partners(rng, base, cap, gamma_P, zP, p_mode)
    NQ4 = _partners(rng, base, cap, gamma_Q, zQ, "amplitude")
    # the sham: SAME mechanism, same channel, independent latent
    SH4 = _partners(rng, base, cap, gamma_S, zS, p_mode)

    controls = np.column_stack([
        np.log(D), np.log(lib), rng.poisson(2.0, n), rng.poisson(3.0, n),
        rng.poisson(1.0, n), np.log1p(rng.poisson(max(base * 0.4, 0.2), n))])
    return dict(NP4=NP4, SH4=SH4, y=NQ4.sum(1).astype(float), D=D,
                log_D=np.log(D), controls=controls, strata=strata,
                donors=donors, cap=cap, zP=zP, p_mode=p_mode,
                gamma_S=gamma_S, base=base)


def state_from(c4):
    return np.hstack([clr(c4), np.log1p(c4.sum(1))[:, None]])


def split(donors, seed=SEED):
    u = sorted(set(donors))
    ev = {d for d in u
          if int(hashlib.sha256(f"{seed}|{d}".encode()).hexdigest()[:8], 16) % 3 == 0}
    return np.isin(donors, list(set(u) - ev)), np.isin(donors, list(ev))


def partial_corr(a, b, c):
    C = np.column_stack([np.ones(len(a)), np.asarray(c).reshape(len(a), -1)])
    ra = a - C @ np.linalg.lstsq(C, a, rcond=None)[0]
    rb = b - C @ np.linalg.lstsq(C, b, rcond=None)[0]
    if ra.std() == 0 or rb.std() == 0:
        return float("nan")
    return float(np.corrcoef(ra, rb)[0, 1])


def one_arm(rng, regime, link, b_sham, seed, want_quality=False):
    d = simulate(rng, link=link, **REGIMES[regime])
    fit, ev = split(d["donors"])
    common = dict(y_count=d["y"], log_D=d["log_D"], controls=d["controls"],
                  strata=d["strata"], donors=d["donors"],
                  fit_mask=fit, eval_mask=ev, seed=seed)
    real = run_directed_test(state=state_from(d["NP4"]), n_perm=0, **common)
    if not np.isfinite(real.median_increment):
        return None

    stats, amps, fams = [], [], list(real.model_families_used)
    for b in range(b_sham):
        sh = _partners(rng, d["base"], d["cap"], d["gamma_S"],
                       rng.normal(0, 1, d["cap"].size), d["p_mode"])
        r = run_directed_test(state=state_from(sh), n_perm=0, **common)
        fams.extend(r.model_families_used)
        if np.isfinite(r.median_increment):
            stats.append(r.median_increment)
            if want_quality and len(amps) < 30:
                amps.append(np.log1p(sh.sum(1)))
    stats = np.asarray(stats, float)
    p = (1 + int((stats >= real.median_increment).sum())) / (1 + stats.size) \
        if stats.size else float("nan")
    qualifies = bool(p <= ALPHA
                     and real.fraction_donors_positive >= DONOR_FRACTION)

    out = {"median_increment": real.median_increment,
           "fraction_donors_positive": real.fraction_donors_positive,
           "sham_null_p": p, "sham_draws": int(stats.size),
           "qualifies": qualifies,
           "model_families": sorted(set(fams)),
           "poisson_fallbacks": int(sum(1 for x in fams if x.endswith("FALLBACK")))}

    if want_quality:
        lc, ld = np.log(d["cap"]), d["log_D"]
        ar = np.log1p(d["NP4"].sum(1))
        real_res = partial_corr(ar, lc, ld)
        sham_res = [partial_corr(a, lc, ld) for a in amps]
        M = np.vstack(amps) if amps else np.zeros((2, 2))
        cc = np.corrcoef(M)
        off = cc[~np.eye(cc.shape[0], dtype=bool)] if cc.ndim == 2 else np.array([0.0])
        # does P's amplitude carry the latent? it must NOT under composition link
        out["sham_quality"] = {
            "real_residual_capture_dependence": real_res,
            "sham_residual_capture_dependence_median": float(np.median(sham_res)),
            "residual_capture_gap": float(real_res - np.median(sham_res)),
            "max_abs_pairwise_sham_correlation": float(np.max(np.abs(off))),
            "pairwise_correlation_is_expected_not_a_defect": (
                "shams correlate with each other because they all carry the "
                "shared capture factor - and so does the real program. A valid "
                "null requires EXCHANGEABILITY with the real statistic under "
                "H0, not mutual independence. Shams drawn iid conditional on "
                "capture are exchangeable. The NEG calibration rate is the "
                "empirical evidence; this number is a diagnostic."),
            "P_amplitude_vs_latent_spearman": float(np.corrcoef(
                np.log1p(d["NP4"].sum(1)), d["zP"])[0, 1]),
            "note": "under a composition link P_amplitude_vs_latent must be "
                    "near zero, else the arm is not testing composition",
        }
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--b-sham", type=int, default=99)
    ap.add_argument("--calibration-datasets", type=int, default=20)
    ap.add_argument("--calibration-b-sham", type=int, default=49)
    ap.add_argument("--regimes", default=",".join(REGIMES))
    a = ap.parse_args()
    if os.path.exists(a.out_dir) and os.listdir(a.out_dir):
        raise SystemExit("STOP_OUTPUT_EXISTS")
    os.makedirs(a.out_dir, exist_ok=True)
    regimes = [r.strip() for r in a.regimes.split(",") if r.strip()]

    results, calib = {}, {}
    for reg in regimes:
        print(f"\n=== regime {reg}  {REGIMES[reg]} ===", flush=True)
        results[reg] = {}
        for arm, cfg in ARMS.items():
            rng = np.random.default_rng(SEED + hash((reg, arm)) % 100000)
            r = one_arm(rng, reg, cfg["link"], a.b_sham, SEED, want_quality=True)
            if r is None:
                results[reg][arm] = {"status": "NO_RESULT"}
                print(f"  {arm:9s} NO RESULT", flush=True); continue
            r["required_qualification"] = cfg["want"]
            r["arm_pass"] = (r["qualifies"] == cfg["want"])
            results[reg][arm] = r
            q = r["sham_quality"]
            print(f"  {arm:9s} want={str(cfg['want']):5s} inc={r['median_increment']:+.4f} "
                  f"p={r['sham_null_p']:.4f} donors+={r['fraction_donors_positive']:.2f} "
                  f"qual={str(r['qualifies']):5s} -> {'PASS' if r['arm_pass'] else 'FAIL'}",
                  flush=True)
            print(f"            sham quality: residual-capture real {q['real_residual_capture_dependence']:+.3f} "
                  f"sham {q['sham_residual_capture_dependence_median']:+.3f} "
                  f"gap {q['residual_capture_gap']:+.3f} | max |r| between shams "
                  f"{q['max_abs_pairwise_sham_correlation']:.3f} | P-amp vs latent "
                  f"{q['P_amplitude_vs_latent_spearman']:+.3f}", flush=True)

        # calibration: NEG false-qualification rate in this regime
        hits = used = 0
        for i in range(a.calibration_datasets):
            rng = np.random.default_rng(SEED + 7919 * (i + 1) + hash(reg) % 9973)
            r = one_arm(rng, reg, "none", a.calibration_b_sham, SEED + i)
            if r is None:
                continue
            used += 1; hits += int(r["qualifies"])
        rate = hits / used if used else float("nan")
        calib[reg] = {"datasets": used, "neg_qualified": hits, "neg_fp_rate": rate}
        print(f"  CALIBRATION NEG: {hits}/{used} = {rate:.3f}", flush=True)

    arms_ok = all(v.get("arm_pass", False)
                  for reg in results for v in results[reg].values())
    fp_ok = all(c["neg_fp_rate"] <= 0.15 for c in calib.values()
                if np.isfinite(c["neg_fp_rate"]))
    no_fallback = all(v.get("poisson_fallbacks", 0) == 0
                      for reg in results for v in results[reg].values())
    gate = bool(arms_ok and fp_ok and no_fallback)

    receipt = {
        "schema": "V5_TEACHER_FIDELITY_SYNTHETIC_GATE_V3",
        "status": "SYNTHETIC_ONLY__NO_REAL_EXPRESSION_READ__NO_TRAINING",
        "protocol": "V29_TEACHER_FIDELITY_FROZEN_PROTOCOL_V7_20260927.md",
        "fixes_over_v2": [
            "sham generated by the SAME MECHANISM, driven by the latent capture "
            "factor, not reconstructed from the observed denominator",
            "POS_COMP arm moves the composition with the total held flat, so the "
            "CLR channel is exercised rather than only the amplitude",
            "estimator fails CLOSED on a negative-binomial fit failure and "
            "records the family actually used",
            "gene-specific capture exponents, so capture is not one clean "
            "shared scalar",
        ],
        "regimes": REGIMES,
        "results": results,
        "calibration": calib,
        "arms_pass": arms_ok,
        "false_positive_bound": 0.15,
        "calibration_pass": fp_ok,
        "no_silent_model_fallback": no_fallback,
        "gate_pass": gate,
        "stopping_rule": (
            "protocol v7 pre-commits this as the LAST attempt to qualify the "
            "count-based readout. If a negative arm remains systematically "
            "positive, the readout is recorded INSUFFICIENTLY_IDENTIFIABLE "
            "under the tested nuisance conditions and work moves to the "
            "composition experiment. No further adjustment of thresholds, "
            "matching rules or control definitions."),
        "training_authorized": False,
    }
    receipt["producer_sha256"] = sha_file(os.path.abspath(__file__))
    p = os.path.join(a.out_dir, "TEACHER_FIDELITY_SYNTHETIC_GATE_V3.json")
    with open(p, "w") as fh:
        json.dump(receipt, fh, indent=2)

    print(f"\n  arms pass {arms_ok} | calibration pass {fp_ok} | "
          f"no silent fallback {no_fallback}")
    print(f"  GATE: {'PASS' if gate else 'FAIL'}")
    print(f"\nwrote {p}")
    return 0 if gate else 1


if __name__ == "__main__":
    sys.exit(main())
