#!/usr/bin/env python3
"""Independent-validator-gated successive-level shared ladder adjudication."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd


def sha(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 << 20), b""):
            h.update(block)
    return h.hexdigest()


def paired_heldout(path: Path, dimension: int) -> np.ndarray:
    table = pd.read_csv(path / "SHARED_DONOR_HELDOUT_PREDICTABILITY.csv")
    take = table[table.dimension.eq(dimension)].pivot(index="donor_index", columns="sketch", values="heldout_predictability")
    return take[["A", "B"]].mean(axis=1).to_numpy()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--previous-analytic", required=True)
    parser.add_argument("--previous-selection", required=True)
    parser.add_argument("--current-analytic", required=True)
    parser.add_argument("--current-selection", required=True)
    parser.add_argument("--current-independent", required=True)
    parser.add_argument("--harness", required=True)
    parser.add_argument("--selector-harness-v2", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    pa, ps, ca, cs, independent, harness, selector_harness_v2, out = map(lambda x: Path(x).resolve(), [args.previous_analytic, args.previous_selection, args.current_analytic, args.current_selection, args.current_independent, args.harness, args.selector_harness_v2, args.out])
    out.mkdir(parents=True, exist_ok=False)
    previous = json.loads((ps / "SHARED_DIMENSION_SELECTION_LEVEL_REFIT_CORRECTED.json").read_text())
    current = json.loads((cs / "SHARED_DIMENSION_SELECTION_LEVEL_REFIT_CORRECTED.json").read_text())
    independent_result = json.loads((independent / "INDEPENDENT_SHARED_VALIDATION.json").read_text())
    contract = json.loads((harness / "JEPA_SCIENTIFIC_PROMOTION_HARNESS_V1.json").read_text())
    selector_tests = json.loads((selector_harness_v2 / "SHARED_D_HARNESS_V2_TEST_REPORT.json").read_text())
    scripts = Path(__file__).resolve().parent
    current_selector_hash = sha(scripts / "correct_full104_phase2_shared_selection_with_refit_null.py")
    current_validator_hash = sha(scripts / "independent_validate_full104_phase2_shared_level.py")
    for label, selection in (("previous", previous), ("current", current)):
        if selection.get("input_hashes", {}).get("code") != current_selector_hash:
            raise RuntimeError(f"{label} selection was not generated by the active selector code")
    if independent_result.get("input_hashes", {}).get("code") != current_validator_hash:
        raise RuntimeError("independent result was not generated by the active validator code")
    if selector_tests.get("status") != "PASS_SHARED_D_HARNESS_V2" or selector_tests.get("input_hashes", {}).get("production_selector_file") != current_selector_hash:
        raise RuntimeError("current contiguous-prefix selector harness is unavailable")
    if independent_result["status"] != "PASS_INDEPENDENT_SHARED_VALIDATOR" or independent_result["candidate_D_shared"] != current["candidate_D_shared"]:
        raise RuntimeError("independent validator gate unavailable")
    if contract["status"] != "FROZEN_PROSPECTIVELY_BEFORE_LEVEL2_SHARED_STATISTICS" or current["sample_level"] != previous["sample_level"] + 1:
        raise RuntimeError("ladder authority mismatch")
    pc, cc = previous["candidate_D_shared"], current["candidate_D_shared"]
    comparison = None; stable = False
    if pc is not None and cc is not None:
        p_interval, c_interval = previous["one_se_dimension_interval"], current["one_se_dimension_interval"]
        interval_overlap = max(p_interval[0], c_interval[0]) <= min(p_interval[1], c_interval[1])
        d = max(int(pc), int(cc))
        overlaps, floors = {}, {}
        for label in "AB":
            pb = np.load(pa / f"SHARED_OVERCOMPLETE_BASIS_{label}.npz", allow_pickle=False)
            cb = np.load(ca / f"SHARED_OVERCOMPLETE_BASIS_{label}.npz", allow_pickle=False)
            pq, _ = np.linalg.qr(pb["components"][:, :d], mode="reduced"); cq, _ = np.linalg.qr(cb["components"][:, :d], mode="reduced")
            overlaps[label] = float(np.square(pq.T @ cq).sum() / d)
            boot = np.load(ca / f"SHARED_BOOTSTRAP_{label}.npz", allow_pickle=False)["observed_stability"][:, d - 1]
            floors[label] = float(boot.mean() - boot.std(ddof=1) / math.sqrt(len(boot)))
        pv, cv = paired_heldout(pa, d), paired_heldout(ca, d)
        current_se = float(cv.std(ddof=1) / math.sqrt(len(cv)))
        predictability_saturated = float(pv.mean()) >= float(cv.mean() - current_se)
        no_subspace_loss = all(overlaps[label] >= floors[label] for label in "AB")
        stable = bool(interval_overlap and predictability_saturated and no_subspace_loss)
        comparison = {
            "previous_level": previous["sample_level"], "current_level": current["sample_level"],
            "previous_candidate_D": pc, "current_candidate_D": cc, "comparison_dimension": d,
            "dimension_intervals_overlap": interval_overlap,
            "principal_angle_subspace_overlap": overlaps, "current_bootstrap_one_se_floor": floors,
            "no_material_subspace_loss": no_subspace_loss,
            "previous_paired_heldout_predictability": float(pv.mean()), "current_paired_heldout_predictability": float(cv.mean()),
            "current_donor_se": current_se, "previous_within_one_current_donor_se": predictability_saturated,
            "paired_donor_delta_mean": float((cv - pv).mean()), "paired_donor_delta_se": float((cv - pv).std(ddof=1) / math.sqrt(len(cv))),
            "successive_level_stable": stable,
        }
    final_level = int(current["sample_level"]) == 4
    result = {
        "schema": "full104-shared-ladder-refit-harness-v1",
        "status": "QUALIFIED_SHARED_CANDIDATE_AWAITING_COUNCIL" if stable else ("FULL104_REACHED_NOT_CONVERGED" if final_level else "ADVANCE_LADDER"),
        "result_state": "QUALIFIED" if stable else "PROVISIONAL",
        "candidate_D_shared": cc if stable else None,
        "current_level_candidate_D": cc,
        "successive_level_converged": stable,
        "next_level_required": not stable and not final_level,
        "full104_reached": final_level,
        "frozen": False,
        "downstream_consumable": False,
        "comparison": comparison,
        "independent_validator_pass": True,
        "input_hashes": {
            "previous_analytic": sha(pa / f"SHARED_LEVEL{previous['sample_level']}_ANALYTIC_DIAGNOSTIC_MANIFEST.csv"),
            "previous_selection": sha(ps / "SHARED_SELECTION_REFIT_CORRECTION_MANIFEST.csv"),
            "current_analytic": sha(ca / f"SHARED_LEVEL{current['sample_level']}_ANALYTIC_DIAGNOSTIC_MANIFEST.csv"),
            "current_selection": sha(cs / "SHARED_SELECTION_REFIT_CORRECTION_MANIFEST.csv"),
            "independent": sha(independent / "INDEPENDENT_SHARED_VALIDATION_MANIFEST.csv"),
            "harness": sha(harness / "JEPA_SCIENTIFIC_PROMOTION_HARNESS_V1_MANIFEST.csv"), "code": sha(Path(__file__)),
        },
    }
    result_path = out / "SHARED_LADDER_REFIT_ADJUDICATION.json"; result_path.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    manifest = out / "SHARED_LADDER_REFIT_ADJUDICATION_MANIFEST.csv"; files = [result_path, Path(__file__)]
    pd.DataFrame([{"path": str(path), "bytes": path.stat().st_size, "sha256": sha(path)} for path in files]).to_csv(manifest, index=False, lineterminator="\n")
    (out / "SHARED_LADDER_REFIT_ADJUDICATION_ROOT_SHA256.txt").write_text(sha(manifest) + "\n", encoding="ascii")
    print(json.dumps({"status": result["status"], "result_state": result["result_state"], "manifest_sha256": sha(manifest)}, indent=2))


if __name__ == "__main__":
    main()
