#!/usr/bin/env python3
"""Write the job queues for V79 real-data inference from the committed benchmark (fold count) for
run_v79_queue.sh. Every job runs a gated runner, so a queue launched before the gates pass refuses job by job.

  fits queue:    full fits A, B, B0; held-out PPC folds for A, B, B0 and the no-donor-class runs for A, B (Q5);
                 merges and support
  phase C queue: folds for both families, the frozen choice, the winner's fit (launched after the
                 zero-truncated NB recovery passes, its extra gate)
  d1 queue:   nested Bayesian-bootstrap workers (single-threaded numpy) and the merge
Usage: make_v79_real_queue.py <python> <out_dir> [d1_workers]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
XLA = 'XLA_FLAGS="--xla_force_host_platform_device_count=4 --xla_cpu_multi_thread_eigen=false"'
ONE_THREAD = "OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1"


def main() -> None:
    py, out = sys.argv[1], Path(sys.argv[2])
    workers = int(sys.argv[3]) if len(sys.argv) > 3 else 4
    bench = json.loads((ROOT / "results/v79/V79_COMPUTE_BENCHMARK_V1.json").read_text(encoding="utf-8"))
    k = bench["rules_applied"]["held_out_folds"]
    s = (HERE.as_posix() + "/").replace("D:/", "/d/")
    run = lambda script, args: f'{XLA} "{py}" "{s}{script}" {args}'  # noqa: E731
    fits = ["# V79 real-data fits (generated by make_v79_real_queue.py)",
            run("run_v79_inference.py", "--phase B0"), run("run_v79_inference.py", "--phase A"),
            run("run_v79_inference.py", "--phase B")]
    for ph in ("A", "B", "B0"):
        fits += [run("run_v79_ppc_heldout.py", f"fold --phase {ph} --fold {f}") for f in range(k)]
    for ph in ("A", "B"):
        fits += [run("run_v79_ppc_heldout.py", f"fold --phase {ph} --fold {f} --without dk") for f in range(k)]
    fits += ["WAIT"]
    fits += [run("run_v79_ppc_heldout.py", f"merge --phase {ph}") for ph in ("A", "B", "B0")]
    fits += [run("run_v79_ppc_heldout.py", f"merge --phase {ph} --without dk") for ph in ("A", "B")]
    fits += ["WAIT"]
    fits += [run("run_v79_ppc_heldout.py", f"support --phase {ph}") for ph in ("A", "B")]
    pc = ["# V79 Phase C (generated by make_v79_real_queue.py)"]
    for fam in ("ztnb", "lognormal"):
        pc += [run("run_v79_phase_c.py", f"fold --family {fam} --fold {f}") for f in range(k)]
    pc += ["WAIT", run("run_v79_phase_c.py", "choose"), "WAIT", run("run_v79_phase_c.py", "full --family auto")]
    d1 = ["# V79 D1 nested Bayesian bootstrap (generated by make_v79_real_queue.py)"]
    d1 += [f'{ONE_THREAD} "{py}" "{s}run_v79_bayesboot.py" worker --workers {workers} --worker {w}'
           for w in range(workers)]
    d1 += ["WAIT", f'"{py}" "{s}run_v79_bayesboot.py" merge']
    out.mkdir(parents=True, exist_ok=True)
    for name, lines in (("queue_fits.txt", fits), ("queue_phase_c.txt", pc), ("queue_d1.txt", d1)):
        with open(out / name, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(lines) + "\n")
    print("folds", k, "fit jobs", sum(1 for x in fits if x and x[0] != "#" and x != "WAIT"), "d1 workers", workers)


if __name__ == "__main__":
    main()
