#!/usr/bin/env python3
"""Render docs/agent/V79_BAYESIAN_GEOMETRY_REPORT_V1.md from the committed V79 records (never typed by hand).

Every number in the report is read from a record and every record is cited with its SHA-256. Sections:
provenance (branch, commit, contract, custody, environment), qualification and benchmark, simulation recovery,
convergence per real fit, variance decomposition (A, B, C, B0), detection versus positive magnitude, donor-class
support (Q5), the nested-Bayesian-bootstrap geometry (T5 and the rest, with the historical bands beside it),
held-out posterior predictive checks, the scrubbed artifact, failures and the non-authorization statement.
Missing records are listed as missing, never filled in.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
import v79_firewall as FW  # noqa: E402

R = ROOT / "results/v79"
I = R / "internal"
OUT = ROOT / "docs/agent/V79_BAYESIAN_GEOMETRY_REPORT_V1.md"
NL = chr(10)


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def load(p: Path):
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def cite(p: Path) -> str:
    return f"`{p.relative_to(ROOT).as_posix()}` (sha256 `{sha(p)[:16]}`)" if p.exists() else \
        f"`{p.relative_to(ROOT).as_posix()}` (MISSING)"


def f3(x) -> str:
    return "n/a" if x is None else f"{x:.3f}"


def git(*args) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True).stdout.strip()


def frac_table(rec, title) -> list:
    L = [f"### {title}", ""]
    if rec is None:
        return L + ["Record missing.", ""]
    att = rec.get("attempts", [])
    L.append("Sampler: " + "; ".join(f"target_accept {a['target_accept']}: {round(a['seconds'])} s, divergences "
                                     f"{sum(a['divergences'])}, worst R-hat {a['worst_rhat']:.4f}, worst ESS "
                                     f"{round(a['worst_ess'])}" for a in att) + ".")
    L.append(f"Converged under the contract: **{rec['diagnosed']}**. {rec['interpretation']}.")
    L.append("")
    if not rec["diagnosed"]:
        return L
    if rec.get("responses"):
        L += ["| component | " + " | ".join(rec["responses"]) + " |", "|---|" + "---|" * len(rec["responses"])]
        for c, f in rec["fractions"].items():
            L.append(f"| {c} | " + " | ".join(f"{f3(f['per_gene_median'][i])} [{f3(f['per_gene_q05'][i])}, "
                                              f"{f3(f['per_gene_q95'][i])}]" for i in range(len(rec["responses"])))
                     + " |")
    else:
        L += ["| component | across-gene median fraction: posterior 5% / 50% / 95% |", "|---|---|"]
        for c, f in rec["fractions"].items():
            q = f["across_gene_median_q"]
            L.append(f"| {c} | {f3(q[0])} / {f3(q[1])} / {f3(q[2])} |")
    return L + [""]


def main() -> None:
    contract = ROOT / "docs/agent/BAYESIAN_SYNTHETIC_GEOMETRY_CONTRACT_V1.json"
    custody = R / "V79_CORRECTED_TRAIN_CUSTODY_RECEIPT_V1.json"
    bench = R / "V79_COMPUTE_BENCHMARK_V1.json"
    L = ["# V79 Bayesian dataset geometry of corrected S174 TRAIN: report V1", "",
         "Generated by `scripts/v79/report_v79.py` from the committed records; every number is read from a cited "
         "record.", "",
         "**Authority:** `" + FW.LANE_TERMINAL + "`. An estimation result, not synthetic authorization; no target "
         "winner, no representation winner, no JEPA training, no E4, no protected-data or production authority.", "",
         "## Provenance", "",
         f"- Branch `{git('rev-parse', '--abbrev-ref', 'HEAD')}`, commit `{git('rev-parse', 'HEAD')}` at render time.",
         f"- Contract {cite(contract)}.", f"- Custody receipt {cite(custody)}.", f"- Compute benchmark {cite(bench)}.",
         ""]
    b = load(bench)
    if b:
        ra = b["rules_applied"]
        L += [f"Gene count rule: **{ra['gene_count']}** genes (projected fit {round(ra['projected_fit_seconds'] or 0)} s); "
              f"held-out folds: **{ra['held_out_folds']}**. JAX {b['environment']['jax']}, "
              f"{b['environment']['platform']}.", ""]
    L += ["## Simulation recovery", ""]
    for lik in ("gaussian", "bernoulli", "ztnb"):
        p = R / f"V79_SIMULATION_RECOVERY_{lik}.json"
        r = load(p)
        L.append(f"- {lik}: {cite(p)}" + ("" if not r else ": " + ", ".join(
            f"{k} {'PASS' if v['pass_'] else 'FAIL'}" for k, v in (r.get("criteria") or {}).items())))
    L += ["", "## Variance decomposition (realized finite-population fractions)", ""]
    L += frac_table(load(I / "V79_PHASE_A_INTERNAL_V1.json"), "Phase A: log1p CP10K (Gaussian)")
    L += frac_table(load(I / "V79_PHASE_B_INTERNAL_V1.json"), "Phase B: detection (Bernoulli-logit, residual pi^2/3)")
    choice = load(I / "phase_c/V79_PHASE_C_FAMILY_CHOICE_INTERNAL_V1.json")
    if choice:
        L += [f"Phase C family choice: **{choice['decision']}**."]
        if choice["comparison"]:
            c = choice["comparison"]
            L += [f"Held-out lpd per positive observation: " + ", ".join(f"{k} {v:.4f}" for k, v in c["score"].items())
                  + f" over {c['n_observations']} observations from {c['n_donors']} donors; paired difference (ztnb "
                  f"minus log-normal) {c['diagnostic']['mean_paired_difference_ztnb_minus_lognormal']:.4f}, "
                  f"donor-clustered SE {c['diagnostic']['donor_clustered_se']:.4f} (diagnostic only)."]
        L.append("")
    L += frac_table(load(I / "phase_c/V79_PHASE_C_INTERNAL_V1.json"), "Phase C: positive magnitude given detection")
    L += frac_table(load(I / "V79_PHASE_B0_INTERNAL_V1.json"), "Phase B0: depth and detected features")
    L += ["## Donor-class support (Q5)", ""]
    for ph in ("A", "B"):
        r = load(I / f"ppc/V79_DONOR_CLASS_SUPPORT_{ph}_INTERNAL_V1.json")
        if r:
            c = r["comparison"]
            L.append(f"- Phase {ph}: held-out lpd difference per observation {c['mean_difference_per_observation']:.5f}, "
                     f"donor-clustered SE {c['donor_clustered_se']:.5f}, both runs converged "
                     f"{c['both_runs_diagnosed']}: **{'supported' if c['supported'] else 'not supported'}** "
                     "(two-SE convention).")
        else:
            L.append(f"- Phase {ph}: record missing.")
    L += ["", "## Geometry: nested Bayesian bootstrap (D1)", ""]
    d1 = load(I / "d1/V79_PHASE_D1_INTERNAL_V1.json")
    if d1:
        L += [f"{d1['draws']} draws; {d1['method']}.", "",
              "| statistic | full-data point | posterior 5% / 50% / 95% | shift (median - point) | historical band |",
              "|---|---|---|---|---|"]
        for k, v in d1["statistics"].items():
            hb = v.get("historical_band")
            L.append(f"| {k} | {v['point']:.4g} | {v['q05']:.4g} / {v['median']:.4g} / {v['q95']:.4g} | "
                     f"{v['resampling_shift']:.3g} | {'' if hb is None else f'[{hb[0]:.4g}, {hb[1]:.4g}]'} |")
        L.append("")
    else:
        L += ["Record missing.", ""]
    L += ["## Held-out-donor posterior predictive checks", "",
          "Share of units whose observed value lies in its central 90% predictive interval (pooled over folds). A "
          "share far below 0.9 marks the model inadequate for that statistic; nothing was tuned. Correlation "
          "statistics were expected to fail (no gene-gene residual dependence in A-C).", ""]
    for ph in ("A", "B", "B0"):
        r = load(I / f"ppc/V79_HELDOUT_PPC_{ph}_INTERNAL_V1.json")
        if not r:
            L.append(f"- Phase {ph}: record missing.")
            continue
        L.append(f"- Phase {ph} (all folds converged: {r['all_folds_diagnosed']}): " + ", ".join(
            f"{k} {f3(v['share_inside'])}" for k, v in r["pooled_share_inside"].items()))
    art = R / "V79_SYNTHETIC_GEOMETRY_ARTIFACT_V1.json"
    L += ["", "## Scrubbed synthetic-consumable artifact", "", f"{cite(art)}; passes `v79_firewall.scrub`.", "",
          "## Failures and corrections", "",
          "Recorded in `docs/agent/V79_SELF_AUDIT_LOG.md` as they happened; nothing rewritten after the fact.", "",
          "## Not authorized", "",
          "TD replay, target inference, 353 ID remediation, E4, JEPA training, optimizer/EMA/runtime changes, "
          "TEST/Morabito, Stage 4, 500K, production selection. V78 untouched.", ""]
    with open(OUT, "w", encoding="utf-8", newline=NL) as fh:
        fh.write(NL.join(L))
    print("report written", OUT.name)


if __name__ == "__main__":
    main()
