"""Adversarial suites for the GSE311359 ID-keyed producer and comparability v2.

Every fixture must make the producer exit NONZERO, asserted on exit status
rather than message text. Each suite opens with a positive control, because a
rejection is only meaningful if the healthy case passes.

Fixtures are synthetic 10x-format triples (barcodes / features / matrix.mtx.gz)
and synthetic registries, built in temp directories. Nothing touches the
authenticated store or any committed evidence.

The load-bearing case is `test_phantom_unit_signature_rejected`: it plants the
exact V1 defect — a guide feature that acquires cells while contributing zero
counts — and requires the producer to refuse. That defect shipped silently once;
this is the test that would have caught it.
"""

from __future__ import annotations

import gzip
import json
import os
import subprocess
import sys
import tempfile

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(REPO, "analysis", "therapeutic_perturbation_etl", "scripts")
GSE311359 = os.path.join(SCRIPTS, "build_gse311359_id_keyed_effects_v2.py")
COMPARABILITY = os.path.join(SCRIPTS, "build_cross_study_comparability_matrix_v2.py")

SAMPLES = ["S1", "S2", "S3", "S4", "S5", "S6", "S7"]
GSM = {"S1": "GSM9324129", "S2": "GSM9324130", "S3": "GSM9324131",
       "S4": "GSM9324132", "S5": "GSM9324133", "S6": "GSM9324134",
       "S7": "GSM9324135"}

# 3 genes + 3 guides (1 target x 2 elements, 1 non-targeting)
BASE_FEATURES = [
    ("ENSG0001", "GENEA", "Gene Expression"),
    ("ENSG0002", "GENEB", "Gene Expression"),
    ("ENSG0003", "GENEC", "Gene Expression"),
    ("TGT_enh_1", "TGT", "CRISPR Guide Capture"),
    ("TGT_enh_2", "TGT", "CRISPR Guide Capture"),      # shares display name
    ("non-targeting_00000", "non-targeting_00000", "CRISPR Guide Capture"),
]
N_CELLS = 6


def write_gz_lines(path, lines):
    with gzip.open(path, "wt", newline="") as fh:
        for l in lines:
            fh.write(l + "\n")


def build_sample(d, s, features, entries, n_cells=N_CELLS):
    """entries: list of (feature_row_1based, cell_1based, value)"""
    pref = os.path.join(d, "%s_%s" % (GSM[s], s))
    write_gz_lines(pref + "_barcodes.tsv.gz",
                   ["CELL%03d-1" % i for i in range(n_cells)])
    write_gz_lines(pref + "_features.tsv.gz",
                   ["\t".join(f) for f in features])
    body = ["%%MatrixMarket matrix coordinate integer general",
            "%%generated by test fixture",
            "%d %d %d" % (len(features), n_cells, len(entries))]
    body += ["%d %d %d" % e for e in entries]
    write_gz_lines(pref + "_matrix.mtx.gz", body)


def healthy_entries():
    """Each guide dominates its own cells; every guide also carries gene counts."""
    e = []
    # cells 1,2 -> TGT_enh_1 (row 4); cells 3,4 -> TGT_enh_2 (row 5);
    # cells 5,6 -> non-targeting (row 6)
    for cell, grow in ((1, 4), (2, 4), (3, 5), (4, 5), (5, 6), (6, 6)):
        e.append((grow, cell, 50))               # dominant guide UMI
        for gene_row in (1, 2, 3):
            e.append((gene_row, cell, 20 + gene_row + cell))
    return e


def build_store(tmp, features=None, entries=None, samples=None):
    d = os.path.join(tmp, "extract")
    os.makedirs(d, exist_ok=True)
    for s in (samples or SAMPLES):
        build_sample(d, s, features or BASE_FEATURES, entries or healthy_entries())
    return d


def run311(extract_dir, out_dir):
    return subprocess.run(
        [sys.executable, GSE311359, "--extract-dir", extract_dir,
         "--out-dir", out_dir], capture_output=True, text=True).returncode


# ==========================================================================
# GSE311359 ID-keyed producer
# ==========================================================================
def test_positive_control_healthy_fixture_exits_zero():
    with tempfile.TemporaryDirectory() as tmp:
        assert run311(build_store(tmp), os.path.join(tmp, "out")) == 0


def test_phantom_unit_signature_rejected():
    """THE V1 DEFECT: a guide acquires cells but contributes zero gene counts."""
    with tempfile.TemporaryDirectory() as tmp:
        e = []
        for cell, grow in ((1, 4), (2, 4), (3, 5), (4, 5), (5, 6), (6, 6)):
            e.append((grow, cell, 50))
        # gene counts ONLY for cells assigned to enh_1 and the control;
        # cells 3 and 4 (enh_2) get none -> that unit reports cells, zero counts
        for cell in (1, 2, 5, 6):
            for gene_row in (1, 2, 3):
                e.append((gene_row, cell, 30))
        assert run311(build_store(tmp, entries=e), os.path.join(tmp, "out")) != 0


def test_duplicate_feature_ids_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        f = list(BASE_FEATURES)
        f[4] = ("TGT_enh_1", "TGT", "CRISPR Guide Capture")   # duplicate ID
        assert run311(build_store(tmp, features=f), os.path.join(tmp, "out")) != 0


def test_feature_tables_differing_across_samples_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        d = os.path.join(tmp, "extract")
        os.makedirs(d, exist_ok=True)
        for s in SAMPLES:
            f = list(BASE_FEATURES)
            if s == "S4":                       # one sample drifts
                f[0] = ("ENSG9999", "GENEZ", "Gene Expression")
            build_sample(d, s, f, healthy_entries())
        assert run311(d, os.path.join(tmp, "out")) != 0


def test_feature_row_order_swap_rejected():
    """Same feature set, permuted order: pooling across samples becomes unsafe."""
    with tempfile.TemporaryDirectory() as tmp:
        d = os.path.join(tmp, "extract")
        os.makedirs(d, exist_ok=True)
        for s in SAMPLES:
            f = list(BASE_FEATURES)
            if s == "S6":
                f[0], f[1] = f[1], f[0]
            build_sample(d, s, f, healthy_entries())
        assert run311(d, os.path.join(tmp, "out")) != 0


def test_negative_count_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        e = healthy_entries() + [(1, 1, -5)]
        assert run311(build_store(tmp, entries=e), os.path.join(tmp, "out")) != 0


def test_nnz_header_mismatch_rejected():
    """Declared nnz disagrees with the number of entries actually present."""
    with tempfile.TemporaryDirectory() as tmp:
        d = os.path.join(tmp, "extract")
        os.makedirs(d, exist_ok=True)
        for s in SAMPLES:
            build_sample(d, s, BASE_FEATURES, healthy_entries())
        # corrupt one sample's header count
        pref = os.path.join(d, "%s_%s" % (GSM["S2"], "S2"))
        with gzip.open(pref + "_matrix.mtx.gz", "rt") as fh:
            lines = fh.read().splitlines()
        hdr = lines[2].split()
        lines[2] = "%s %s %d" % (hdr[0], hdr[1], int(hdr[2]) + 7)
        write_gz_lines(pref + "_matrix.mtx.gz", lines)
        assert run311(d, os.path.join(tmp, "out")) != 0


def test_wrong_feature_dimension_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        d = os.path.join(tmp, "extract")
        os.makedirs(d, exist_ok=True)
        for s in SAMPLES:
            build_sample(d, s, BASE_FEATURES, healthy_entries())
        pref = os.path.join(d, "%s_%s" % (GSM["S3"], "S3"))
        with gzip.open(pref + "_matrix.mtx.gz", "rt") as fh:
            lines = fh.read().splitlines()
        hdr = lines[2].split()
        lines[2] = "%d %s %s" % (int(hdr[0]) + 3, hdr[1], hdr[2])
        write_gz_lines(pref + "_matrix.mtx.gz", lines)
        assert run311(d, os.path.join(tmp, "out")) != 0


def test_missing_sample_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        d = build_store(tmp, samples=[s for s in SAMPLES if s != "S5"])
        assert run311(d, os.path.join(tmp, "out")) != 0


def test_occupied_output_directory_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        d = build_store(tmp)
        out = os.path.join(tmp, "out")
        os.makedirs(out)
        with open(os.path.join(out, "prior.json"), "w") as fh:
            fh.write("{}")
        assert run311(d, out) != 0


def test_not_matrixmarket_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        d = build_store(tmp)
        pref = os.path.join(d, "%s_%s" % (GSM["S1"], "S1"))
        write_gz_lines(pref + "_matrix.mtx.gz", ["NOT A MATRIX MARKET FILE"])
        assert run311(d, os.path.join(tmp, "out")) != 0


def test_colliding_display_names_do_not_collapse():
    """Positive behavioural check: two guides sharing a name stay separate."""
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, "out")
        assert run311(build_store(tmp), out) == 0
        with open(os.path.join(out, "GSE311359_ID_KEYED_RECEIPT_V2.json")) as fh:
            rec = json.load(fh)
        assert rec["display_name_collisions"] == {"TGT": ["TGT_enh_1", "TGT_enh_2"]}
        assert rec["phantom_units_detected"] == 0
        # 2 target elements + 1 control, across 7 samples
        assert rec["units_with_cells"] == 21
        assert rec["perturbed_units"] == 14 and rec["nt_units"] == 7


# ==========================================================================
# comparability matrix v2
# ==========================================================================
def _registry(tmp, studies, drop_exposure=None, drop_study=None):
    e = {}
    for s in studies:
        if s == drop_study:
            continue
        e[s] = {"etl_status": "X", "outcome_exposure": "" if s == drop_exposure
                else "INSPECTED_DEVELOPMENT", "biological_estimability": "Y",
                "source_reference": "t", "reviewer": "t", "asserted_on": "2026-09-25"}
    p = os.path.join(tmp, "reg.json")
    with open(p, "w") as fh:
        json.dump({"registry_id": "T", "assertions": e}, fh)
    return p


REAL = os.path.join(REPO, "analysis", "therapeutic_perturbation_etl")
METADATA_CONTRACT = os.path.join(REAL, "evidence",
                                 "CROSS_STUDY_METADATA_ASSERTION_CONTRACT_V1.json")
REAL_INPUTS = [
    "--gse335887-ref", os.path.join(REAL, "reference", "gse335887",
                                    "GSE335887_itf_feature_reference.csv.gz"),
    "--gse178317-lib", os.path.join(REAL, "reference",
                                    "GSE178317_sgrna_library_suppl_table5.csv"),
    "--gse311359-identity", os.path.join(REAL, "evidence", "gse311359",
                                         "GSE311359_perturbation_identity.csv"),
]
PB = "D:/jepa_perturb_outputs_20260923/gse301119_rawpb_v1"
ALL_STUDIES = ["GSE178317", "GSE335887", "GSE301119", "GSE311359", "GSE293118",
               "GSE254205", "GSE240609", "GSE241858", "GSE175721"]

inputs_present = all(os.path.exists(REAL_INPUTS[i]) for i in (1, 3, 5)) and \
    os.path.exists(os.path.join(PB, "CRISPRi_guide_donor_meta.csv"))


def runcmp(registry, out_dir, contract=None):
    return subprocess.run(
        [sys.executable, COMPARABILITY, *REAL_INPUTS,
         "--gse301119-crispri", os.path.join(PB, "CRISPRi_guide_donor_meta.csv"),
         "--gse301119-crispra", os.path.join(PB, "CRISPRa_guide_donor_meta.csv"),
         "--assertion-registry", registry,
         "--metadata-contract", contract or METADATA_CONTRACT,
         "--out-dir", out_dir],
        capture_output=True, text=True).returncode


def _contract(tmp, drop_field=None, empty=False):
    """Copy the real metadata contract, optionally damaged."""
    with open(METADATA_CONTRACT) as fh:
        c = json.load(fh)
    if empty:
        c["assertions"] = {}
    elif drop_field:
        first = sorted(c["assertions"])[0]
        c["assertions"][first][drop_field] = ""
    p = os.path.join(tmp, "contract.json")
    with open(p, "w") as fh:
        json.dump(c, fh)
    return p


@pytest.mark.skipif(not inputs_present, reason="real inputs not on this machine")
def test_comparability_positive_control():
    with tempfile.TemporaryDirectory() as tmp:
        assert runcmp(_registry(tmp, ALL_STUDIES), os.path.join(tmp, "o")) == 0


@pytest.mark.skipif(not inputs_present, reason="real inputs not on this machine")
def test_comparability_rejects_study_missing_from_registry():
    with tempfile.TemporaryDirectory() as tmp:
        r = _registry(tmp, ALL_STUDIES, drop_study="GSE240609")
        assert runcmp(r, os.path.join(tmp, "o")) != 0


@pytest.mark.skipif(not inputs_present, reason="real inputs not on this machine")
def test_comparability_rejects_blank_exposure():
    """A study present but carrying no exposure value must not default silently."""
    with tempfile.TemporaryDirectory() as tmp:
        r = _registry(tmp, ALL_STUDIES, drop_exposure="GSE240609")
        assert runcmp(r, os.path.join(tmp, "o")) != 0


@pytest.mark.skipif(not inputs_present, reason="real inputs not on this machine")
def test_comparability_refuses_occupied_output():
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, "o")
        os.makedirs(out)
        with open(os.path.join(out, "prior.csv"), "w") as fh:
            fh.write("x")
        assert runcmp(_registry(tmp, ALL_STUDIES), out) != 0


@pytest.mark.skipif(not inputs_present, reason="real inputs not on this machine")
def test_comparability_rejects_empty_metadata_contract():
    with tempfile.TemporaryDirectory() as tmp:
        assert runcmp(_registry(tmp, ALL_STUDIES), os.path.join(tmp, "o"),
                      contract=_contract(tmp, empty=True)) != 0


@pytest.mark.skipif(not inputs_present, reason="real inputs not on this machine")
@pytest.mark.parametrize("field", ["intervention", "cell_model", "controls",
                                   "assay_readout", "source"])
def test_comparability_rejects_incomplete_metadata_contract(field):
    """Self-audit S3: assertions live in an external contract and must be complete."""
    with tempfile.TemporaryDirectory() as tmp:
        assert runcmp(_registry(tmp, ALL_STUDIES), os.path.join(tmp, "o"),
                      contract=_contract(tmp, drop_field=field)) != 0
