import hashlib

import numpy as np
import pytest

import sea_ad_jepa.v5.full104_rare_tail_molecular_primitives_v1 as P


def test_distance_matrix_matches_tie_aware_sign_concordance() -> None:
    # Pad to 2048 coordinates so the frozen >=256-informative gate is satisfied.
    a = np.zeros((3, 2048), dtype=np.int8)
    a[0, :4] = [1, 1, -1, 0]
    a[1, :4] = [1, -1, -1, 0]
    a[2, :4] = [0, 0, 0, 0]
    # Make coordinates 4..259 jointly informative and identical.
    a[0, 4:260] = 1
    a[1, 4:260] = 1
    a[2, 4:260] = 1

    d = P.distance_matrix(a)
    assert d.shape == (3, 3)
    # Pair 0/1 differs only at coordinate 1 among 259 informative coords:
    # sign difference magnitude 2 -> divided by 2 => one discordant unit.
    assert d[0, 1] == pytest.approx(1 / 259)
    assert np.allclose(d, d.T, equal_nan=True)
    assert np.allclose(np.diag(d), 0.0)


def test_nearest_half_uses_distance_then_selection_row_tiebreak() -> None:
    d = np.array(
        [
            [0.0, 0.2, 0.2, 0.3, 0.4],
            [0.2, 0.0, 0.1, 0.1, 0.5],
            [0.2, 0.1, 0.0, 0.2, 0.5],
            [0.3, 0.1, 0.2, 0.0, 0.5],
            [0.4, 0.5, 0.5, 0.5, 0.0],
        ]
    )
    rows = np.array([100, 30, 20, 40, 50])
    # Anchor0 has four candidates; nearest half keeps 2. Distance tie 1/2 is
    # broken by selection_row, so local index 2 (row20) precedes 1 (row30).
    got = P.nearest_half_candidates(d, anchor=0, selection_rows=rows)
    assert got.tolist() == [2, 1]


def test_isolation_score_is_furthest_member_inside_nearest_half() -> None:
    d = np.array(
        [
            [0.0, 0.1, 0.2, 0.4],
            [0.1, 0.0, 0.3, 0.5],
            [0.2, 0.3, 0.0, 0.6],
            [0.4, 0.5, 0.6, 0.0],
        ]
    )
    rows = np.array([10, 20, 30, 40])
    scores, candidates = P.isolation_scores_and_candidates(d, rows)
    # Three finite others -> ceil(3/2)=2.
    assert candidates[0].tolist() == [1, 2]
    assert scores[0] == pytest.approx(0.2)


def test_deterministic_flat_sample_is_unique_capped_and_replayable() -> None:
    a = P.deterministic_flat_sample(10_000, namespace="fixture")
    b = P.deterministic_flat_sample(10_000, namespace="fixture")
    assert a == b
    assert len(a) == 64
    assert len(set(a)) == 64
    assert min(a) >= 0 and max(a) < 10_000
    assert P.deterministic_flat_sample(5, namespace="fixture") == (0, 1, 2, 3, 4)


def test_tail_triplet_sampling_respects_q95_and_64_cap() -> None:
    n = 100
    rows = np.arange(1000, 1000 + n)
    # Simple finite distance geometry with every anchor's ranking determined by
    # absolute local-index separation.
    ix = np.arange(n)
    d = np.abs(ix[:, None] - ix[None, :]).astype(float)
    triplets = P.select_tail_triplets(
        z_distance=d,
        selection_rows=rows,
        panel=0,
        source_code=1,
        fold_index=2,
        donor_code=7,
        operator_code=35,
    )
    assert len(triplets) <= 64
    assert len(set(triplets)) == len(triplets)
    for i, j, k in triplets:
        assert i != j and i != k and j != k
        assert rows[j] < rows[k]


def test_matching_blocks_cover_rows_once_and_avoid_terminal_singleton() -> None:
    n = 17
    rows = np.arange(100, 100 + n)
    library = np.linspace(1000, 2000, n)
    detected = np.linspace(200, 500, n)[::-1]
    blocks = P.build_depth_detection_blocks(
        selection_rows=rows,
        source_library=library,
        detected_count=detected,
    )
    flat = np.concatenate(blocks)
    assert sorted(flat.tolist()) == list(range(n))
    assert len(np.unique(flat)) == n
    # Historical rule merges a one-element final chunk into the prior chunk.
    assert all(len(b) != 1 for b in blocks)


def test_matched_y_permutation_is_one_to_one_replayable_and_nonzero_per_block() -> None:
    blocks = (
        np.array([0, 1, 2, 3]),
        np.array([4, 5, 6, 7]),
    )
    a = P.matched_y_permutation(
        n_rows=8,
        blocks=blocks,
        panel=1,
        q=17,
        source_code=2,
        fold_index=3,
        donor_code=44,
        operator_code=31,
    )
    b = P.matched_y_permutation(
        n_rows=8,
        blocks=blocks,
        panel=1,
        q=17,
        source_code=2,
        fold_index=3,
        donor_code=44,
        operator_code=31,
    )
    assert np.array_equal(a, b)
    assert sorted(a.tolist()) == list(range(8))
    assert not np.any(a[:4] == np.arange(4))
    assert not np.any(a[4:] == np.arange(4, 8))


def test_gene_and_pair_hash_serialization_is_little_endian_int32(monkeypatch) -> None:
    # Synthetic 10k-address common set; patch expected hashes to the exact
    # little-endian int32 serialization generated by the frozen slices.
    common = np.arange(10_000, dtype=np.int64)
    ranked = P.ranked_common(common)
    expected_gene = {}
    expected_pair = {}
    for panel in (0, 1):
        expected_gene[panel] = {}
        expected_pair[panel] = {}
        for view, (start, end) in P.PANEL_VIEW_RANK_SLICES[panel].items():
            genes = ranked[start:end]
            expected_gene[panel][view] = hashlib.sha256(
                genes.astype("<i4").tobytes()
            ).hexdigest()
            positions, addresses = P.select_pairs(genes, panel=panel, view=view)
            assert positions.shape == (2048, 2)
            expected_pair[panel][view] = hashlib.sha256(
                addresses.astype("<i4").tobytes()
            ).hexdigest()

    monkeypatch.setattr(P, "PANEL_GENE_SHA256", expected_gene)
    monkeypatch.setattr(P, "PANEL_PAIR_ADDRESS_SHA256", expected_pair)

    for panel in (0, 1):
        views = P.select_gene_views(common, panel)
        for view in ("Z", "X", "Y"):
            _, addresses = P.select_pairs(views[view], panel=panel, view=view)
            assert P.verify_pair_address_hash(
                addresses, panel=panel, view=view
            ) == expected_pair[panel][view]
