"""Bounded MRA-JEPA v4 mechanics contracts."""

from .checkpointing import capture_synthetic_checkpoint, restore_synthetic_checkpoint
from .calibration import (
    covariance_calibration,
    gradient_l2_norm,
    variance_floor_calibration,
)
from .contracts import (
    MECHANICS_CONTRACT,
    MICROBATCH_COLLAPSE_TELEMETRY_POLICY,
    VisibilityMasks,
    derive_visibility_masks,
)
from .ema import (
    EMAOptimizerStepController,
    EMATargetEncoder,
    EMAUpdateSummary,
    create_ema_target,
    ema_momentum_at_step,
    ema_target_module,
    update_ema_target,
    validate_momentum,
)
from .gene_tokenizer import GeneExpressionTokenizer
from .losses import frozen_target_copy, jepa_prediction_loss, variance_floor_penalty
from .perceiver_encoder import (
    GeneSetMechanicsEncoder,
    LatentTransformerBlock,
    PerceiverCrossAttention,
    V4AEncoderSkeleton,
)
from .predictor import LatentPredictor
from .pca_summary import FrozenPCA, flatten_slots
from .masking import construct_context_mask, keyed_mask_seed
from .teacher_student_checkpoint import (
    CHECKPOINT_SCHEMA,
    capture_checkpoint,
    load_checkpoint_verified,
    restore_checkpoint,
    save_checkpoint_atomic,
)
from .teacher_student_movement import (
    adjudicate_module,
    adjudicate_tensor,
    decay_only_counterfactual,
    enforce_module_movement,
)
from .teacher_student_runtime import (
    BACKBONE_REGISTRY_SHA256,
    F1B_ATTACK_AUTHORITY_ROOT,
    FROZEN_BACKBONE_REGISTRY,
    FROZEN_PREDICTOR_REGISTRY,
    HEALTHY_TEACHER_BASE_ROOT,
    POPULATION_ACCESS_ROOT,
    PREDICTOR_REGISTRY_SHA256,
    PRODUCTION_CONFIG,
    TeacherStudentConfig,
    TeacherStudentModules,
    build_teacher_student_components,
    enforce_adam_moments,
    enforce_unscaled_gradient_gates,
    production_update,
    sample_uniform_target_blocks,
    validate_production_config,
)
from .telemetry import (
    EMAParameterHealth,
    EMAUpdateTelemetry,
    RepresentationHealth,
    TargetLatentHealth,
    context_target_agreement,
    ema_parameter_health,
    ema_update_telemetry,
    module_parameter_snapshot,
    online_target_parameter_distance,
    representation_health,
    singular_spectrum_metrics,
    target_latent_health,
)

__all__ = [
    "BACKBONE_REGISTRY_SHA256",
    "CHECKPOINT_SCHEMA",
    "EMAOptimizerStepController",
    "EMAParameterHealth",
    "EMATargetEncoder",
    "EMAUpdateSummary",
    "EMAUpdateTelemetry",
    "F1B_ATTACK_AUTHORITY_ROOT",
    "FROZEN_BACKBONE_REGISTRY",
    "FROZEN_PREDICTOR_REGISTRY",
    "GeneExpressionTokenizer",
    "FrozenPCA",
    "GeneSetMechanicsEncoder",
    "HEALTHY_TEACHER_BASE_ROOT",
    "LatentPredictor",
    "LatentTransformerBlock",
    "MECHANICS_CONTRACT",
    "MICROBATCH_COLLAPSE_TELEMETRY_POLICY",
    "POPULATION_ACCESS_ROOT",
    "PREDICTOR_REGISTRY_SHA256",
    "PRODUCTION_CONFIG",
    "PerceiverCrossAttention",
    "RepresentationHealth",
    "TargetLatentHealth",
    "TeacherStudentConfig",
    "TeacherStudentModules",
    "V4AEncoderSkeleton",
    "VisibilityMasks",
    "adjudicate_module",
    "adjudicate_tensor",
    "build_teacher_student_components",
    "capture_checkpoint",
    "capture_synthetic_checkpoint",
    "construct_context_mask",
    "context_target_agreement",
    "covariance_calibration",
    "create_ema_target",
    "decay_only_counterfactual",
    "derive_visibility_masks",
    "ema_parameter_health",
    "ema_momentum_at_step",
    "ema_target_module",
    "ema_update_telemetry",
    "enforce_adam_moments",
    "enforce_module_movement",
    "enforce_unscaled_gradient_gates",
    "frozen_target_copy",
    "flatten_slots",
    "gradient_l2_norm",
    "jepa_prediction_loss",
    "keyed_mask_seed",
    "load_checkpoint_verified",
    "module_parameter_snapshot",
    "online_target_parameter_distance",
    "production_update",
    "representation_health",
    "restore_checkpoint",
    "restore_synthetic_checkpoint",
    "sample_uniform_target_blocks",
    "save_checkpoint_atomic",
    "singular_spectrum_metrics",
    "target_latent_health",
    "update_ema_target",
    "validate_momentum",
    "validate_production_config",
    "variance_floor_penalty",
    "variance_floor_calibration",
]
